### ISSUE TITLE
Php 5.6 compatibility ?

### ISSUE THREAD

**Issue by QuentinBrosse** [bpolaszek/guzzle-throttle-middleware#1]
Hi! :)

Could a Php 5.6 compatibility be considered?
For the moment some parts of your code are not compatible (e.g. typing, null coalesce operator).

Thanks ! :)

**Comment by bpolaszek** [comment]
Hello @quentinbrosse,

It has been designed with PHP 7+ but I'm not opposed to making it compatible with PHP 5.6.

I'm pretty busy for the moment but feel free to make a PR and I'll look at it ASAP.

Thank you, 
Ben

**Comment by QuentinBrosse** [comment]
Hello,
I'm pretty busy too but it could be a great thing :)
