### ISSUE TITLE
PHP 7.0 version fix isn't tagged

### ISSUE THREAD

**Issue by mreillyorg** [bpolaszek/guzzle-throttle-middleware#3]
Hi,

It looks like you made an 0.4 tag and then added a PHP version fix to 7.0 but didn't tag that commit with a new revision.

So it won't show up on Packagist for Composer.

Could you please fix that? Will mean don't have to do a composer entry to the commit.

Thanks.

**Comment by bpolaszek** [comment]
Hy @mreillyorg, thank you for pointing this out.

0.4.1 has just been published.

Have a nice day,
Ben
