### ISSUE TITLE
Any chance of a release for guzzle 7.x?

### ISSUE THREAD

**Issue by geek-merlin** [bpolaszek/guzzle-throttle-middleware#4]
Current composer.json says this is only compatible with guttle 6.x.

**Comment by bpolaszek** [comment]
Hello there,

Unfortunately it's been years since I stopped using Guzzle in favor of Symfony's HTTP Client, and I'm considering discontinuing this plugin, unless there's a PR for that.

Thanks,
Ben

**Comment by geek-merlin** [comment]
Ah, thanks for clarifying!
